---
# Step 1: Installing containerd
- name: Install package needed
  ansible.builtin.package:
    name:
      - wget
      - tar
    state: present

# Module get_url chỉ download file nếu dest đã tồn tại do force = false theo mặc định
- name: Download containerd file
  ansible.builtin.get_url:
    url: "https://github.com/containerd/containerd/releases/download/v{{ containerd_version }}/containerd-{{ containerd_version }}-{{ containerd_os }}-{{ containerd_arch }}.tar.gz"
    dest: "{{ containerd_download_dir }}/containerd-{{ containerd_version }}-{{ containerd_os }}-{{ containerd_arch }}.tar.gz"
    checksum: "{{ containerd_checksum }}"

# Module command: creates, cmd, chdir (chuyển đến thưc mục này trước khi chạy command)
- name: Extract "containerd-{{ containerd_version }}-{{ containerd_os }}-{{ containerd_arch }}.tar.gz" to /usr/local
  ansible.builtin.command:
    cmd: "tar Cxzvf {{ containerd_dir }} containerd-{{ containerd_version }}-{{ containerd_os }}-{{ containerd_arch }}.tar.gz"
    chdir: "{{containerd_download_dir }}"
    # khi chạy playbook thứ 2 nó sẽ thực hiện lại thao tác giải nén, càn chỉ định nó nếu tệp đã tồn tại thì không cần giải nén nữa
    creates: "{{ containerd_dir }}/bin/containerd"

# Xác định systemd là init system của cgroup của containerd
# Module file dùng để chắc chắn file/directory đã tồn tại trong hệ thống do get_url không tải xuống dest không tồn tại
- name: Ensure "{{ containerd_systemd }}" directory exit
  ansible.builtin.file:
    path: "{{ containerd_systemd }}"
    state: directory
    owner: root
    group: root
    mode: '0644'

# Do là file nhị phân nên mode là 0755
# Thư mục "/usr/lib/systemd/system/" là vị trí chuẩn cho các service thuộc systemd quản lý và được cài đặt bởi các phần mềm hệ thống hoặc package manager như apt/dnf/yum/snapd/...
# Thư mục "/usr/local/lib/systemd/system/" thường được sử dụng cho các service được cài đặt bởi người dùng, được cài đặt từ nguồn không chính thống
- name: Download containerd.service file to start systemd cgroup driver
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/containerd/containerd/main/containerd.service"
    dest: "/usr/local/lib/systemd/system/containerd.service"
    mode: '0755'

- name: Check if /usr/local/bin is in PATH
  ansible.builtin.shell:
    cmd: grep -q "/usr/local/bin" /etc/environment
  ignore_errors: true
  register: path_check

# Sử dụng module lineinfile để thao tác với nội dung của file
- name: Add /usr/local/bin is in PATH in /etc/environment
  ansible.builtin.lineinfile:
    path: /etc/environment
    line: 'export PATH=$PATH:/usr/local/bin'
    insertafter: EOF
    # regexp luôn được kết hợp với insertbefore/insertafter/state=present(default)
    # Nếu không tìm thấy sẽ dựa vào insertbefore/insertafter để xác định thêm vào đầu hay cuối tệp, nếu thấy thì không sử dụng kết quả trường này
    # Theo mặc định insertafter được set thay vì insertbefore nên nếu không tìm thấy line được thêm vào cuois tệp
    # regexp: '^PATH=' (không dùng trong task này)
    state: present
  when: not path_check.rc  # Chỉ thêm dòng nếu /usr/local/bin chưa tồn tại trong PATH

- name: Flush handlers 3
  ansible.builtin.meta: flush_handlers

- name: Reload systemd daemon
  systemd:
    daemon_reload: true

- name: Ensure containerd service start and enabled
  ansible.builtin.service:
    name: containerd
    enabled: yes
    state: started