---
# Forwarding IPv4 and letting iptables see bridged traffic
# Module copy chỉ tạo file 1 lần do đó chạy nhiều lần playbook không ảnh hưởng
- name: Install package needed
  ansible.builtin.package:
    name:
      - wget
      - tar
      - source
    state: present

- name: Load required kernel modules
  ansible.builtin.copy:
    src: k8s_module.conf
    dest: /etc/modules-load.d/k8s.conf
    owner: root
    group: root
    mode: '0644'
  notify: Load Kernel Modules

- name: Flush handlers 1
  ansible.builtin.meta: flush_handlers

- name: Apply sysctl settings
  ansible.builtin.copy:
    src: k8s_systemd.conf
    dest: /etc/sysctl.d/k8s.conf
    owner: root
    group: root
    mode: '0644'
  notify: Apply Sysctl Settings

- name: Flush handlers 2
  ansible.builtin.meta: flush_handlers