---
- name: Load Kernel Modules
  shell: "{{ item }}"
  loop:
    - modprobe overlay
    - modprobe br_netfilter

- name: Apply Sysctl Settings
  command: sysctl --system

- name: Source /etc/environment
  ansible.builtin.command:
    cmd: "source /etc/environment"

- name: Reload containerd
  ansible.builtin.service:
    name: containerd
    state: restarted
