---
# Disable swap config
- name: Disable swap config now on all hosts
  ansible.builtin.command:
    cmd: "swapoff -a"

- name: Comment out swap entry in /etc/fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: '^.*swap.*'
    line: "# {{ item }}"
  with_lines: cat /etc/fstab | grep swap

# Install kubectl
- name: Download kubectl
  ansible.builtin.get_url:
    url: "https://dl.k8s.io/release/v{{ kubectl_version }}/bin/linux/amd64/kubectl"
    dest: "{{ kubectl_download_dir }}/kubectl"
    checksum: "{{ kubectl_checksum }}"

- name: Install kubectl binary
  ansible.builtin.copy:
    src: "{{ kubectl_download_dir }}"
    dest: "{{ kubectl_dir }}"
    remote_src: true
    owner: root
    group: root
    mode: '0755'
