---
- name: Update kubelet service configuration
  ansible.builtin.replace:
    path: /usr/lib/systemd/system/kubelet.service
    regexp: '/usr/bin'
    replace: '/usr/local/bin'
  notify: Restart kubelet service if configuration was updated

- name: Update kubeadme config for kubelet service
  ansible.builtin.replace:
    path: /usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf
    regexp: '/usr/bin'
    replace: '/usr/local/bin'
  notify: Restart kubelet service if configuration was updated

- name: Reload systemd daemon
  systemd:
    daemon_reload: true