---
# containerd package info
containerd_version: 2.0.0-rc.0
containerd_os: linux
containerd_arch: amd64
containerd_checksum: sha256:ed42e8824603660787051f49ae413c8dc109345502072e1be0976824a7ff458e
containerd_download_dir: /tmp
containerd_dir: /usr/local
containerd_systemd: /usr/local/lib/systemd/system

# runc binary info
runc_version: 1.1.12
runc_arch: amd64
runc_checksum: sha256:aadeef400b8f05645768c1476d1023f7875b78f52c7ff1967a6dbce236b8cbd8
runc_download_dir: /tmp
runc_dir: /usr/local/sbin/runc

# CNI plugin package info
cni_version: 1.4.1
cni_os: linux
cni_arch: amd64
cni_checksum: sha256:1511f6c003ace805eafeb1132727791326283cff88a923d76329e1892bba7a10
cni_download_dir: /tmp
cni_dir: /opt/cni/bin
