---
- name: Load Kernel Modules
  command: "{{ item }}"
  loop:
    - modprobe overlay
    - modprobe br_netfilter

- name: Apply Sysctl Settings
  command: sysctl --system

- name: Reload systemd daemon
  systemd:
    daemon_reload: true
  notify: Enabled and start containerd
