---

- name: Update repo cache before doing
  hosts: all
  become: true
  pre_tasks:

  - tags: always
    package:
      update_cache: yes
    changed_when: false

#- name: Install containerd on all hosts
#  hosts: all
#  become: true
#  roles:
#    - install_containerd

- name: Set hostname to all k8s hosts
  hosts: all
  become: true
  tasks:
  - name: Include host vars files
    include_vars:
      dir: host_vars
      name: host_vars

  - name: Run my_role
    include_role:
      name: set_hostname
    vars:
      host_vars: "{{ host_vars }}"