---

- hosts: all
  become: true
  pre_tasks:

  - name: updates repo cache
    tags: always
    package:
      update_cache: yes
    changed_when: false

- hosts: all
  become: true
  roles:
    - install_requirements

- hosts: all
  become: true
  roles:
    - set_host_name

- hosts: web_servers
  become: true
  roles:
    - web_servers

- hosts: db_servers
  become: true
  roles:
    - db_servers

- hosts: file_servers
  become: true
  roles:
    - file_servers