---

- hosts: all
  become: true
  pre_tasks:

  - name: updates repo cache
    tags: always
    package:
      update_cache: yes
    changed_when: false

- hosts: all
  become: true
  roles:
    - install_containerd