---

- name: Update repo cache before doing
  hosts: all
  become: true
  pre_tasks:

  - tags: always
    package:
      update_cache: yes
    changed_when: false

#- name: Install containerd on all hosts
#  hosts: all
#  become: true
#  roles:
#    - install_containerd

- name: Set hostname to all k8s hosts
  hosts: all
  become: true
  vars:
    host_vars_dir: "host_vars"
  vars_files:
    - "{{ host_vars_dir }}/192.168.1.21.yml"
    - "{{ host_vars_dir }}/192.168.1.22.yml"
    - "{{ host_vars_dir }}/192.168.1.23.yml"
    - "{{ host_vars_dir }}/192.168.1.24.yml"
  roles:
    - set_hostname